const router = require('express').Router();
const { User } = require('../../models');
const withAuth = require('../../utils/auth')

// const cloudinary = require("cloudinary").v2;


router.get('/all', async (req, res) => {
    console.log(req.body)
    try {
        const userData = await User.findAll(req.body);
        console.log(userData)
        res.status(200).send(userData)
    } catch (err) {
        res.status(400).json(err);
    }
});

router.post('/', async (req, res) => {
    console.log("router hit")
    console.log(req.body)
    try {
        console.log(req)
        const userData = await User.create(req.body);
        req.session.save(() => {
            req.session.user_id = userData.id;
            req.session.logged_in = true;

            res.status(200).json(userData);
        });
    } catch (err) {
        res.status(400).json(err);
    }
});


//post route to create user's login
router.post('/login', async (req, res) => {
    console.log('i work')
    try {
        const userData = await User.findOne({ where: { email: req.body.email } });

        if (!userData) {
            res
                .status(400)
                .json({ message: 'Incorrect email or password, please try again' });
            return;
        }

        const validPassword = await userData.checkPassword(req.body.password);

        if (!validPassword) {
            res
                .status(400)
                .json({ message: 'Incorrect email or password, please try again' });
            return;
        }

        req.session.save(() => {
            req.session.user_id = userData.id;
            req.session.logged_in = true;

            res.json({ user: userData, message: 'You are now logged in!' });
        });

    } catch (err) {
        res.status(400).json(err);
    }
});
//post routes for login 
//within the post route to login - check if the email and password are valid (checkpassword)
//logout post route (destroy)
router.post('/logout', (req, res) => {
    if (req.session.logged_in) {
        req.session.destroy(() => {
            // res.status(204).end();
            res.status(204).json('You\'re now logged out');
        });
    } else {
        res.status(404).json("You\'re not logged in")
    }
});

// router.post('/images', (req, res) => {
//     console.log('idk')
//     cloudinary.uploader.upload('./1.png', { tags: 'basic_sample' })
//         .then(function (image) {
//             console.log();
//             console.log("** File Upload (Promise)");
//             console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
//             console.log("* " + image.public_id);
//             console.log("* " + image.url);
//         })
//         .catch(function (err) {
//             console.log();
//             console.log("** File Upload (Promise)");
//             if (err) { console.warn(err); }
//         });
// console.log(req.file) // to see what is returned to you
// const image = {};
// image.url = req.file.url;
// image.id = req.file.public_id;
// Image.create(image) // save image information in database
//     .then(newImage => res.json(newImage))
//     .catch(err => console.log(err));



module.exports = router;